// components/Auth/AuthPage.jsx

import { useState, useRef, useMemo, useEffect } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";

import {
  User,
  Phone,
  Mail,
  Fingerprint,
  Map,
  MapPin,
  BuildingComplex,
  Home,
  Hash,
  LockKeyhole,
  Eye,
  EyeOff,
  ArrowRight,
  ArrowLeft,
  ShieldCheck,
  LandPlot,
  Trees,
  Navigation,
  CircleCheck,
  AlertCircle,
} from "lucide-react";

import InputField    from "./InputField";
import PasswordField from "./PasswordField";
import LandVisual    from "./LandVisual";
import OtpField      from "./OtpField";
import CustomSelect  from "./CustomSelect";

import {
  validateField,
  validateEmail,
  sanitizePhone,
  sanitizeAadhaar,
  sanitizePincode,
  validateSignupFields,
  validateLoginFields,
} from "./Validation";

import { useLocation }  from "../../hooks/useLocation";
import { sendOtp, verifyOtp } from "../../services/otpService";
import authStore from "../../store/authStore";

// ─── Component ────────────────────────────────────────────────────────────

export default function AuthPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();

  const tab = searchParams.get("tab");

  const [isSignUp, setIsSignUp] = useState(tab !== "login");
  const [showPassword,   setShowPassword]   = useState(false);
  const [termsAccepted,  setTermsAccepted]  = useState(false);
  const [termsError,     setTermsError]     = useState("");

  // ── Pre-fill email from authStore if arriving on login tab at mount ──────
  // Uses lazy initializer so getAndClearSignupData() runs exactly once.
  const [formData, setFormData] = useState(() => {
    const p = tab !== "login" ? null : authStore.getAndClearSignupData();
    return {
      name: "", phone: "", email: p?.email ?? "",
      aadhaar: "", loginAadhaar: "",
      state: "", stateSlug: "",
      district: "", city: "", pincode: "", password: "",
    };
  });

  // Per-field error messages — empty string means no error
  const [errors, setErrors] = useState({
    name:         "",
    phone:        "",
    email:        "",
    aadhaar:      "",
    loginAadhaar: "",
    pincode:      "",
    password:     "",
  });

  // ── OTP state (shared between signup + login, scoped by isSignUp) ──────
  const [otpValue,    setOtpValue]    = useState("");
  const [otpSentCode, setOtpSentCode] = useState(""); // the code generated by service
  const [otpVerified, setOtpVerified] = useState(false);
  const [otpError,    setOtpError]    = useState("");
  const [isSending,   setIsSending]   = useState(false);

  // Reset OTP state whenever we switch tabs or the email changes
  const resetOtp = () => {
    setOtpValue("");
    setOtpSentCode("");
    setOtpVerified(false);
    setOtpError("");
    setIsSending(false);
  };

  const resetForm = (prefillEmail = "") => {
    setFormData({
      name: "", phone: "", email: prefillEmail,
      aadhaar: "", loginAadhaar: "",
      state: "", stateSlug: "",
      district: "", city: "", pincode: "", password: "",
    });
    setErrors({
      name: "", phone: "", email: "",
      aadhaar: "", loginAadhaar: "",
      pincode: "", password: "",
    });
    setTermsAccepted(false);
    setTermsError("");
    resetOtp();
  };

  // ── Sync isSignUp with URL searchParam (fixes navigate not updating UI) ──
  useEffect(() => {
    const signUp = tab !== "login";
    setIsSignUp(signUp);
    setShowPassword(false);
    // Pre-fill email from authStore when arriving on the login tab
    const pending = !signUp ? authStore.getAndClearSignupData() : null;
    resetForm(pending?.email ?? "");
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);

  // ── Location data (states + districts from API) ────────────────────────
  const { states, districts, statesLoading, districtsLoading } = useLocation(
    formData.stateSlug
  );

  const stateOptions = useMemo(
    () =>
      states.map((s) => ({
        label: s.name.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()),
        value: s.slug,
      })),
    [states]
  );

  const districtOptions = useMemo(
    () =>
      districts.map((d) => ({
        label: d.name.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()),
        value: d.name,
      })),
    [districts]
  );

  // ── Debounce timers ────────────────────────────────────────────────────
  const debounceTimers = useRef({});
  const DEBOUNCE_MS = 600;

  // ── Handle input change ────────────────────────────────────────────────
  const handleChange = (e) => {
    const { name } = e.target;
    let { value } = e.target;

    // Sanitise numeric-only fields
    if (name === "phone")        value = sanitizePhone(value);
    if (name === "aadhaar")      value = sanitizeAadhaar(value);
    if (name === "loginAadhaar") value = sanitizeAadhaar(value);
    if (name === "pincode")      value = sanitizePincode(value);

    // State selection: derive slug, reset district
    if (name === "stateSlug") {
      const matched = states.find((s) => s.slug === value);
      setFormData((prev) => ({
        ...prev,
        state:    matched ? matched.name : value,
        stateSlug: value,
        district:  "",
      }));
    } else {
      setFormData((prev) => ({ ...prev, [name]: value }));
    }

    // If email changes, reset OTP flow
    if (name === "email") resetOtp();

    // Clear field error immediately
    if (errors[name] !== undefined) {
      setErrors((prev) => ({ ...prev, [name]: "" }));
    }

    // Debounced validation
    if (!(name in errors)) return;
    clearTimeout(debounceTimers.current[name]);
    debounceTimers.current[name] = setTimeout(() => {
      if (!value.trim()) return;
      const err = validateField(name, value);
      setErrors((prev) => ({ ...prev, [name]: err }));
    }, DEBOUNCE_MS);
  };

  // ── OTP: Send ──────────────────────────────────────────────────────────
  const handleSendOtp = async () => {
    setIsSending(true);
    setOtpError("");
    try {
      const code = await sendOtp(formData.email);
      setOtpSentCode(code);
    } catch {
      setOtpError("Failed to send OTP. Please try again.");
    } finally {
      setIsSending(false);
    }
  };

  // ── OTP: Verify ────────────────────────────────────────────────────────
  const handleVerifyOtp = () => {
    if (verifyOtp(otpValue, otpSentCode)) {
      setOtpVerified(true);
      setOtpError("");
    } else {
      setOtpError("Invalid OTP. Please check and try again.");
    }
  };

  // ── Submit ─────────────────────────────────────────────────────────────
  const handleSubmit = (e) => {
    e.preventDefault();

    // Block submit if OTP not verified
    if (!otpVerified) {
      setOtpError(
        otpSentCode
          ? "Please verify your OTP before submitting."
          : "Please send and verify the OTP first."
      );
      return;
    }

    if (isSignUp) {
      // ── Check Terms checkbox first ──
      if (!termsAccepted) {
        setTermsError("You must accept the Terms of Service and Privacy Policy.");
        return;
      }
      const newErrors = validateSignupFields(formData);
      setErrors(newErrors);
      const hasErrors = Object.values(newErrors).some((e) => e !== "");
      if (hasErrors) return;

      // Store signup data (including state/district) and redirect to login
      authStore.setSignupData({
        email:     formData.email,
        name:      formData.name,
        state:     formData.state,
        stateSlug: formData.stateSlug,
        district:  formData.district,
      });
      console.log("Sign Up Data:", formData);
      navigate("/auth?tab=login");
    } else {
      const newErrors = validateLoginFields(formData);
      setErrors(newErrors);
      const hasErrors = Object.values(newErrors).some((e) => e !== "");
      if (hasErrors) return;

      // Retrieve signup data so location carries over to map
      const pending = authStore.getAndClearSignupData();
      authStore.setLoggedInUser({
        email:     formData.email,
        name:      pending?.name  ?? "User",
        state:     pending?.state ?? "",
        stateSlug: pending?.stateSlug ?? "",
        district:  pending?.district ?? "",
      });
      console.log("Sign In Data:", {
        email:        formData.email,
        loginAadhaar: formData.loginAadhaar,
      });
      // Redirect to full GIS dashboard on successful login
      navigate("/dashboard");
    }
  };

  // ── Tab switch button (manual toggle) ─────────────────────────────────
  const handleTabSwitch = () => {
    // Navigate via URL — the useEffect will react and reset state
    navigate(isSignUp ? "/auth?tab=login" : "/auth?tab=signup");
  };

  // ── Is the current email valid for the OTP button? ────────────────────
  const emailIsValid = validateEmail(formData.email) === "";

  return (
    <div className="min-h-screen bg-[#f7f8f4] text-[#17251d]">
      {/* Header */}
      <header className="absolute left-0 top-0 z-20 flex w-full items-center justify-between px-6 py-5 lg:px-10">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#1f5c3a] text-white shadow-md">
            <LandPlot size={22} />
          </div>

          <div>
            <h1 className="text-lg font-bold tracking-tight">SmartBhumi</h1>
            <p className="text-[10px] font-medium uppercase tracking-[2px] text-[#718075]">
              Digital Land Governance
            </p>
          </div>
        </div>

        {/* Back to home */}
        <button
          onClick={() => navigate("/")}
          className="flex items-center gap-1.5 rounded-lg border border-[#d5ddd7] bg-white px-4 py-2 text-xs font-semibold text-[#314139] shadow-sm transition hover:border-[#3d7956] hover:text-[#286044]"
        >
          <ArrowLeft className="h-3.5 w-3.5" />
          Back to Home
        </button>
      </header>

      <main className="grid min-h-screen lg:grid-cols-[1fr_1fr]">
        {/* ================= LEFT SIDE ================= */}
        <section className="flex items-center justify-center px-6 pb-6 pt-28 lg:px-14 lg:pt-20">
          <div className="w-full max-w-[590px]">
            {/* Heading */}
            <div className="mb-7">
              <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#e8f0ea] px-3 py-2 text-xs font-semibold text-[#286044]">
                <ShieldCheck size={14} />
                Secure citizen account
              </div>

              <h2 className="text-3xl font-bold tracking-tight text-[#17251d] sm:text-4xl">
                {isSignUp ? "Create your account" : "Welcome back"}
              </h2>

              <p className="mt-2 text-sm text-[#718075]">
                {isSignUp
                  ? "Register to access your digital land records and services."
                  : "Sign in to access your land records and services."}
              </p>
            </div>

            {/* Form */}
            <form onSubmit={handleSubmit} className="space-y-4" noValidate>

              {/* =========== SIGN UP FIELDS =========== */}
              {isSignUp && (
                <>
                  {/* Name + Phone */}
                  <div className="grid gap-4 sm:grid-cols-2">
                    <InputField
                      label="Full Name"
                      name="name"
                      placeholder="Enter your full name"
                      icon={<User size={17} />}
                      value={formData.name}
                      onChange={handleChange}
                      error={errors.name}
                    />
                    <InputField
                      label="Phone Number"
                      name="phone"
                      placeholder="10-digit number"
                      icon={<Phone size={17} />}
                      value={formData.phone}
                      onChange={handleChange}
                      error={errors.phone}
                    />
                  </div>

                  {/* Aadhaar + Email */}
                  <div className="grid gap-4 sm:grid-cols-2">
                    <InputField
                      label="Aadhar number"
                      name="aadhaar"
                      placeholder="XXXX XXXX XXXX"
                      icon={<Fingerprint size={17} />}
                      value={formData.aadhaar}
                      onChange={handleChange}
                      error={errors.aadhaar}
                    />
                    <InputField
                      label="Gmail ID"
                      name="email"
                      type="email"
                      placeholder="example@gmail.com"
                      icon={<Mail size={17} />}
                      value={formData.email}
                      onChange={handleChange}
                      error={errors.email}
                    />
                  </div>

                  {/* OTP field — appears below Gmail */}
                  <OtpField
                    email={formData.email}
                    emailValid={emailIsValid}
                    otpValue={otpValue}
                    onOtpChange={setOtpValue}
                    otpVerified={otpVerified}
                    otpError={otpError}
                    onSendOtp={handleSendOtp}
                    onVerifyOtp={handleVerifyOtp}
                    isSending={isSending}
                  />

                  {/* Location Heading */}
                  <div className="flex items-center gap-2 pt-2">
                    <div className="h-px flex-1 bg-[#dfe5df]" />
                    <span className="flex items-center gap-1.5 px-2 text-[11px] font-semibold uppercase tracking-wider text-[#718075]">
                      <MapPin size={13} />
                      Location Details
                    </span>
                    <div className="h-px flex-1 bg-[#dfe5df]" />
                  </div>

                  {/* State + District */}
                  <div className="grid gap-4 sm:grid-cols-2">
                    <CustomSelect
                      label="State"
                      name="stateSlug"
                      icon={<Map size={17} />}
                      value={formData.stateSlug}
                      onChange={handleChange}
                      options={stateOptions}
                      loading={statesLoading}
                    />
                    <CustomSelect
                      label="District"
                      name="district"
                      icon={<BuildingComplex size={17} />}
                      value={formData.district}
                      onChange={handleChange}
                      options={districtOptions}
                      loading={districtsLoading}
                      disabled={!formData.stateSlug}
                    />
                  </div>

                  {/* City + Pincode */}
                  <div className="grid gap-4 sm:grid-cols-2">
                    <InputField
                      label="City / Village"
                      name="city"
                      placeholder="Enter city or village"
                      icon={<Home size={17} />}
                      value={formData.city}
                      onChange={handleChange}
                    />
                    <InputField
                      label="Pincode"
                      name="pincode"
                      placeholder="Enter 6-digit pincode"
                      icon={<MapPin size={17} />}
                      value={formData.pincode}
                      onChange={handleChange}
                      error={errors.pincode}
                    />
                  </div>
                </>
              )}

              {/* =========== LOGIN FIELDS =========== */}
              {!isSignUp && (
                <>
                  {/* Gmail ID */}
                  <InputField
                    label="Gmail ID"
                    name="email"
                    type="email"
                    placeholder="example@gmail.com"
                    icon={<Mail size={17} />}
                    value={formData.email}
                    onChange={handleChange}
                    error={errors.email}
                  />

                  {/* OTP field */}
                  <OtpField
                    email={formData.email}
                    emailValid={emailIsValid}
                    otpValue={otpValue}
                    onOtpChange={setOtpValue}
                    otpVerified={otpVerified}
                    otpError={otpError}
                    onSendOtp={handleSendOtp}
                    onVerifyOtp={handleVerifyOtp}
                    isSending={isSending}
                  />

                  {/* Aadhaar */}
                  <InputField
                    label="Aadhar Number"
                    name="loginAadhaar"
                    placeholder="XXXX XXXX XXXX"
                    icon={<Fingerprint size={17} />}
                    value={formData.loginAadhaar}
                    onChange={handleChange}
                    error={errors.loginAadhaar}
                  />
                </>
              )}

              {/* Password — shared */}
              <PasswordField
                value={formData.password}
                onChange={handleChange}
                showPassword={showPassword}
                setShowPassword={setShowPassword}
                isSignUp={isSignUp}
                error={errors.password}
              />

              {/* Terms (signup only) */}
              {isSignUp && (
                <div className="space-y-1 pt-1">
                  <div className="flex items-start gap-2">
                    <input
                      id="terms-checkbox"
                      type="checkbox"
                      checked={termsAccepted}
                      onChange={(e) => {
                        setTermsAccepted(e.target.checked);
                        if (e.target.checked) setTermsError("");
                      }}
                      className="mt-0.5 h-4 w-4 rounded border-[#cbd5ce] accent-[#286044] cursor-pointer"
                    />
                    <label
                      htmlFor="terms-checkbox"
                      className="text-[11px] leading-5 text-[#718075] cursor-pointer"
                    >
                      I agree to the{" "}
                      <span className="font-semibold text-[#286044]">Terms of Service</span>{" "}
                      and{" "}
                      <span className="font-semibold text-[#286044]">Privacy Policy</span>.
                    </label>
                  </div>
                  {termsError && (
                    <p className="text-[11px] font-medium text-[#d94040] pl-6">
                      {termsError}
                    </p>
                  )}
                </div>
              )}

              {/* Submit — disabled when OTP not verified */}
              <button
                type="submit"
                disabled={!otpVerified}
                className={`group flex h-11 w-full items-center justify-center gap-2 rounded-lg text-sm font-semibold text-white shadow-sm transition
                  ${otpVerified
                    ? "bg-[#286044] hover:bg-[#1e4e35] hover:shadow-md active:scale-[0.99]"
                    : "bg-[#7aaa8f] cursor-not-allowed"
                  }`}
              >
                {isSignUp ? "Create Account" : "Sign In"}
                <ArrowRight
                  size={17}
                  className="transition-transform group-hover:translate-x-1"
                />
              </button>

              {/* OTP not verified hint below submit */}
              {!otpVerified && (
                <p className="text-center text-[11px] text-[#718075]">
                  Verify your email OTP to enable submission.
                </p>
              )}

              {/* Switch login / signup */}
              <div className="flex items-center justify-center gap-1 pt-2 text-xs text-[#718075]">
                <span>
                  {isSignUp ? "Already have an account?" : "Don't have an account?"}
                </span>
                <button
                  type="button"
                  onClick={handleTabSwitch}
                  className="font-bold text-[#286044] hover:underline"
                >
                  {isSignUp ? "Sign in" : "Create account"}
                </button>
              </div>
            </form>

            {/* Footer */}
            <div className="mt-6 flex items-center justify-between border-t border-[#e0e5e0] pt-5 text-[10px] text-[#8a958e]">
              <span>© 2026, All Rights Reserved by Sp</span>
              <span className="flex items-center gap-1">
                <ShieldCheck size={14} />
                Your data is protected
              </span>
            </div>
          </div>
        </section>

        {/* ================= RIGHT SIDE ================= */}
        <LandVisual />
      </main>
    </div>
  );
}
