// src/services/otpService.js
// ─────────────────────────────────────────────────────────────────────────────
// Mock OTP service — simulates email OTP send/verify with no backend.
// The generated OTP is printed to the browser console so you can test it.
// Swap sendOtp() for a real API call (e.g. Firebase, AWS SES, Nodemailer)
// when a backend is ready — the OtpField UI doesn't need to change at all.
// ─────────────────────────────────────────────────────────────────────────────

const OTP_LENGTH = 4;

/**
 * Simulate sending a 4-digit OTP to the given email address.
 *
 * @param   {string} email
 * @returns {Promise<string>}  Resolves with the generated OTP string.
 */
export async function sendOtp(email) {
  // Generate a zero-padded 4-digit code  e.g. "0472"
  const otp = String(Math.floor(Math.random() * 10 ** OTP_LENGTH)).padStart(
    OTP_LENGTH,
    "0"
  );

  // Simulate a small network delay (300 ms)
  await new Promise((r) => setTimeout(r, 300));

  // In production this would call your email API instead
  console.log(`%c[OtpService] OTP for ${email}: ${otp}`, "color: #286044; font-weight: bold; font-size: 14px;");

  return otp;
}

/**
 * Verify whether the user-entered OTP matches the one that was sent.
 *
 * @param {string} enteredOtp  What the user typed
 * @param {string} realOtp     What was generated by sendOtp()
 * @returns {boolean}
 */
export function verifyOtp(enteredOtp, realOtp) {
  return enteredOtp.trim() === realOtp.trim();
}
