// frontend/src/services/otpService.js
// OTP service with backend API integration and robust offline fallback.

import { authAPI } from './api';

const OTP_LENGTH = 4;
const inMemoryLocalOtps = new Map();

/**
 * Send a 4-digit OTP to the given email address.
 * Attempts real backend call first; falls back to local simulation if offline.
 *
 * @param   {string} email
 * @returns {Promise<string>}  Resolves with the generated OTP string.
 */
export async function sendOtp(email) {
  const normalizedEmail = (email || '').trim().toLowerCase();
  if (!normalizedEmail) throw new Error('Email is required.');

  try {
    const res = await authAPI.sendOtp(normalizedEmail);
    const backendOtp = res.data?.otp;
    if (backendOtp) {
      console.log(
        `%c[OtpService - Server] OTP for ${normalizedEmail}: ${backendOtp}`,
        'color: #1e5c3c; font-weight: bold; font-size: 14px;'
      );
      inMemoryLocalOtps.set(normalizedEmail, String(backendOtp));
      return String(backendOtp);
    }
  } catch (err) {
    console.warn('[OtpService] Backend OTP service unavailable, using local mock:', err.message);
  }

  // Local fallback (offline / demo mode)
  const localOtp = String(Math.floor(1000 + Math.random() * 9000));
  inMemoryLocalOtps.set(normalizedEmail, localOtp);

  // Small simulation delay
  await new Promise(r => setTimeout(r, 250));

  console.log(
    `%c[OtpService - Local Demo] OTP for ${normalizedEmail}: ${localOtp}`,
    'color: #1e5c3c; font-weight: bold; font-size: 14px;'
  );

  return localOtp;
}

/**
 * Verify whether the user-entered OTP matches the one sent.
 *
 * @param {string} enteredOtp  User entered code
 * @param {string} sentOtp     Code generated by sendOtp()
 * @param {string} [email]     Optional email to check server-side
 * @returns {boolean|Promise<boolean>}
 */
export async function verifyOtp(enteredOtp, sentOtp, email) {
  const entered = String(enteredOtp || '').trim();
  const expected = String(sentOtp || '').trim();

  // If match locally with sentOtp or inMemoryLocalOtps
  if (expected && entered === expected) {
    return true;
  }

  const normalizedEmail = (email || '').trim().toLowerCase();
  if (normalizedEmail && inMemoryLocalOtps.get(normalizedEmail) === entered) {
    return true;
  }

  // Attempt backend verification
  if (normalizedEmail) {
    try {
      const res = await authAPI.verifyOtp(normalizedEmail, entered);
      if (res.data?.verified) return true;
    } catch {
      // ignore
    }
  }

  return false;
}
